### PR TITLE
test: Added a test example for issue #18.

### PR DESCRIPTION
**Pull request by ckaran**
I think I've found part of the issue that causes issue #18. I've created a new
project under 'issues' to illustrate the problem.  The README has more
information on it.

### CODE REVIEW

**Comment by camshaft** [comment]
Nice find! I think that should be an easy enough fix by not wrapping the generator code in the unwind handler.

**Comment by ckaran** [comment]
Sounds good!  It'll certainly help when debugging what went wrong in manual implementations of `TypeGenerator`...

**Comment by ckaran** [comment]
I hate to press, but do you have an idea as to when you'll have a fix in place?

**Comment by camshaft** [comment]
I'll try to get to it this week. I've been busy with other things.

**Comment by ckaran** [comment]
I understand, and I apologize about pushing you.  Thank you for getting to it when you can.

**Comment by ckaran** [comment]
*ping*

**Comment by camshaft** [comment]
I've got a test added for this now. Thanks for the help in reproducing this!

**Comment by ckaran** [comment]
Glad you got it in!  Honestly, it was giving me enough of a headache that I had to stop using bolero for a bit, and I honestly started to worry that you'd abandoned the project.  Glad it's still going though, bolero is a *fantastic* way to test code!

**Comment by camshaft** [comment]
Definitely not abandoned! Just other projects taking priority 🙂. Anyway, I'll get a release with these fixes out soon

**Comment by ckaran** [comment]
> Definitely not abandoned! Just other projects taking priority slightly_smiling_face. Anyway, I'll get a release with these fixes out soon

Thank you!

**Pull request closed without merging**
