### PR TITLE
Allow setting corpus and crashes dirs in cargo bolero test

### LINKED ISSUE #84: Allow defining the location for corpus and artifacts directories
Hey! I'm thinking of adding an option to `cargo bolero test` that'd allow setting where one wants the corpus and artifacts directories, as it seems like it already sets that in a way that's independent of the fuzzing engine used. Would you be interested in getting it upstream?

### PR DESCRIPTION
**Pull request by Ekleog**
Fixes #84

### CODE REVIEW

**Comment by Ekleog** [comment]
Probably bumping the MSRV further would fix things, as stable tests pass properly in CI? But I'm not sure that's something you're willing to do, so I'm not adding that to the PR right now :)

**Comment by camshaft** [comment]
The MSRV policy is a rolling 6+ month window so I'll need to figure out another fix for that. But the corpus override seems reasonable to me.

**Comment by Ekleog** [comment]
Hmm ok thanks!

What's weird is I think I had already hit this exact issue with cargo-fuzz when the version of cargo-fuzz and the version of rustc didn't have the same LLVM version, but I had seemed to notice that cargo-bolero, for a reason I'm not sure of, didn't hit this issue. My guess had been that cargo-bolero did LLVM version autodetection, but I'm not sure if it's actually true given I'm seeing this now :/

**Comment by Ekleog** [comment]
AFAICT rust 1.57.0 was released more than 6 months ago (Dec 2, 2021), so hopefully this would be good to go? :)

**Comment by camshaft** [comment]
It should be now!

**Review by camshaft — APPROVED** [review]

**Pull request merged**
