### PR TITLE
Remove toolchain auto-detection

### PR DESCRIPTION
**Pull request by Ekleog**
Before this, when running cargo-bolero in a way that requires nightly, it would implicitly not use the toolchain that was explicitly provided.

For instance, if running `cargo +nightly-2022-06-20 bolero test foo`, it would still use `cargo +nightly` to compile.

This is unexpected (especially when the `nightly` toolchain is not installed under this name), and there is an easy way for the user to work around and recover the current behavior, ie. just typing `cargo +nightly`.

To the best of my understanding, just removing these two lines should be enough to come back to the behavior of "just use the caller-provided toolchain".

Does that make sense to you?

### CODE REVIEW

**Comment by Ekleog** [comment]
Hmm the test failure looks pretty much unrelated to this PR, or did I miss something?

**Comment by camshaft** [comment]
I'm not sure about this change. It's nice to have the tool auto-select the toolchain depending on what you need. To opt out of this behavior, you should be able to pass the `--toolchain default` argument and it should inherit the user-specified toolchain.

**Comment by camshaft** [comment]
I think I was able to address this issue by only forcing nightly if the current version is using stable

https://github.com/camshaft/bolero/blob/5b3fc33543435ee917f2ca13cf4be3c2cf9b8680/cargo-bolero/src/project.rs#L81-L84

Does this fix your issue?

**Comment by camshaft** [comment]
I think you're right. The goal of bolero is to be as "native" to your regular Rust development workflow. And the tool chain detection is definitely a non-standard feature in that. If someone wants to remove it with a PR, that would be great (or update this PR). Otherwise I can do it when I have time.

**Comment by Ekleog** [comment]
Awesome! I've just updated the PR :)

**Comment by Ekleog** [comment]
(test ubuntu-afl failed ; I'm force-pushing to force a CI rerun)

**Comment by Ekleog** [comment]
Seems like there are intermittent failures but the `(1.57.0, ubuntu-latest, afl, NONE)` one appears to be quite consistent.

@camshaft As it doesn't seem related to this PR at all, do you have any idea what it could be related to?

**Comment by Ekleog** [comment]
Looks like this was unrelated to this PR indeed: force-pushing the same code just successfully passed tests, so it was certainly an intermittent. (and it seems there are still some intermittents today given my other in-flight PRs, but force-pushing a few times seems to make them pass now)

@camshaft do you want to land this now that tests pass? :)

**Pull request merged**
